In [1]:
from src.pandas_pattern_generator import PandasPatternGenerator
from src.lsh import LSHashMap, hamming_dist, norm_vectors
from src.bloom_count import bloom
from src.pattern_overlap import pattern_overlap

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from dask.dataframe.hyperloglog import compute_hll_array
import itertools


In [2]:
BITS = 8
NPats = 8

ppg = PandasPatternGenerator(1000, 10)

overlaps = np.asarray([ppg.get_overlap(x, y) for x,y in itertools.product(*[range(1, NPats + 1)]*2)])
overlaps = overlaps.reshape(NPats, NPats).T

In [3]:
overlaps

array([[1000,  500,  334,  250,  200,  167,  143,  125],
       [ 500,  500,  167,  250,  100,  167,   72,  125],
       [ 334,  167,  334,   84,   67,  167,   48,   42],
       [ 250,  250,   84,  250,   50,   84,   36,  125],
       [ 200,  100,   67,   50,  200,   34,   29,   25],
       [ 167,  167,  167,   84,   34,  167,   24,   42],
       [ 143,   72,   48,   36,   29,   24,  143,   18],
       [ 125,  125,   42,  125,   25,   42,   18,  125]])

In [8]:
patterns = np.asarray([ppg.generate_pattern(x) for x in range(1, NPats + 1)])

tmp = pattern_overlap(patterns, LSHwidth=32)

overlaps_close, neighbor_sets = tmp.get_overlaps(max_ham_distance=10)

print('neighbor_sets  = ', neighbor_sets)
print('overlaps = \n', overlaps_close)

neighbor_sets  =  {(2, 3, 5, 6, 7), (0, 1, 4)}
overlaps = 
 [[1000  501    0    0  201    0    0    0]
 [ 501  500    0    0  142    0    0    0]
 [   0    0  334  138    0  169   78   55]
 [   0    0  138  250    0  112   53  129]
 [ 201  142    0    0  200    0    0    0]
 [   0    0  169  112    0  167   50   61]
 [   0    0   78   53    0   50  143   22]
 [   0    0   55  129    0   61   22  125]]


---